### ISSUE TITLE
Test install broken

### ISSUE THREAD

**Issue by TsunayoshiSawada** [devCU/IPS-4.4-BitTracker#3]
Did a simple test install to check it out as instructions arent given i simply pasted it under applications and clicked installed via the admin panel. 
Result came out kinda like this 

![image](https://user-images.githubusercontent.com/34431649/81405505-691d5880-9155-11ea-8b96-114064324d21.png)

Not sure i did it right but would like to give it a test spin if anyone can guide me a bit.

**Comment by ZooKeeper-star** [comment]
I think this is dead, no one is answering.

**Comment by GaalexxC** [comment]
The data directory is incompetent cause these are mostly dev builds, so lang bits, database tables and settings are not 100% and data is missing or incomplete

Here is a clue on the project homepage
![dev](https://user-images.githubusercontent.com/28851458/89364803-53aac280-d6a1-11ea-879d-30d0e9d5093c.PNG)

Posted a small update here, wish I could do more guys but don't have the time right now.
https://github.com/devCU/IPS-4.4-BitTracker/issues/4#issuecomment-668936825

**Comment by ZooKeeper-star** [comment]
Waiting patiently on updates…Thank you kindly.  Sent from Mail for Windows 10 From: Gary CornellSent: Tuesday, August 4, 2020 10:27 PMTo: devCU/IPS-4.4-BitTrackerCc: ZooKeeper-star; CommentSubject: Re: [devCU/IPS-4.4-BitTracker] Test install broken (#3) The data directory is incompetent cause these are mostly dev builds, so lang bits, database tables and settings are not 100% and data is missing or incompleteHere is a clue on the project homepagePosted a small update here, wish I could do more guys but don't have the time right now.#4 (comment)—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
