### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by ZooKeeper-star** [devCU/IPS-4.4-BitTracker#4]
I am interested in updates, when it will be ready? beta testing...

**Comment by GaalexxC** [comment]
Sorry for the late replay. To answer your question yes and no, in other words it is still a active project but has been put on the back burner for the past several months due to the current climate here. IE: COVID-19 and employment (Unemployment better describes this), had and have sick family members, thankfully all doing well and not working at my regular job so freelancing anywhere and everywhere. Just don't have the time right now. Hoping August brings better days ahead and get back to this and my other free time open source projects.

I have done some work on it here and there and will refresh the repository later this week.

**Comment by ZooKeeper-star** [comment]
I am willing to send funds to get this completed.Let me know what it would take to get this done. Thank you  Sent from Mail for Windows 10 From: Gary CornellSent: Tuesday, August 4, 2020 10:21 PMTo: devCU/IPS-4.4-BitTrackerCc: ZooKeeper-star; AuthorSubject: Re: [devCU/IPS-4.4-BitTracker] Is this still alive? (#4) Sorry for the late replay. To answer your question yes and no, in other words it is still a active project but has been put on the back burner for the past several months due to the current climate here. IE: COVID-19 and employment (Unemployment better describes this), had and have sick family members, thankfully all doing well and not working at my regular job so freelancing anywhere and everywhere. Just don't have the time right now. Hoping August brings better days ahead and get back to this and my other free time open source projects.I have done some work on it here and there and will refresh the repository later this week.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZooKeeper-star** [comment]
Thank you kindly for the update. Sent from Mail for Windows 10 From: Gary CornellSent: Tuesday, August 4, 2020 10:21 PMTo: devCU/IPS-4.4-BitTrackerCc: ZooKeeper-star; AuthorSubject: Re: [devCU/IPS-4.4-BitTracker] Is this still alive? (#4) Sorry for the late replay. To answer your question yes and no, in other words it is still a active project but has been put on the back burner for the past several months due to the current climate here. IE: COVID-19 and employment (Unemployment better describes this), had and have sick family members, thankfully all doing well and not working at my regular job so freelancing anywhere and everywhere. Just don't have the time right now. Hoping August brings better days ahead and get back to this and my other free time open source projects.I have done some work on it here and there and will refresh the repository later this week.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZooKeeper-star** [comment]
Any update? Were waiting patiently.Thank you kindly.  Sent from Mail for Windows 10 From: Gary CornellSent: Tuesday, August 4, 2020 10:21 PMTo: devCU/IPS-4.4-BitTrackerCc: ZooKeeper-star; AuthorSubject: Re: [devCU/IPS-4.4-BitTracker] Is this still alive? (#4) Sorry for the late replay. To answer your question yes and no, in other words it is still a active project but has been put on the back burner for the past several months due to the current climate here. IE: COVID-19 and employment (Unemployment better describes this), had and have sick family members, thankfully all doing well and not working at my regular job so freelancing anywhere and everywhere. Just don't have the time right now. Hoping August brings better days ahead and get back to this and my other free time open source projects.I have done some work on it here and there and will refresh the repository later this week.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GaalexxC** [comment]
@ZooKeeper-star  whats with the css in your posts?

Anyway updating the files to 4.4.10 this weekend which will be the final release of the 4.4 tracker obviously since IPS is moving to 4.5 now. Don't expect too many bells and whistles right now like free leech and stuff. People can easily expand and create plugins later on.

BTW we have dropped public tracker usage as this is a secure and private tracker NOT meant to index torrents from other sites or trackers, you HAVE to run your own domain as the tracker or don't bother with this application.

There will be a short beta test this week at the test site before devcu supporters release and then a public release to follow.

**Comment by ZooKeeper-star** [comment]
Its because I am replying from my email.Basic, private tracker is all we need.Were already running xbt on another forum software., but I dislike the forum software and can’t wait to get this forum to IPS, like the others we have.Thank you for the update. Is their I can contact you privately? I sent you  a message on facebook messages.   Sent from Mail for Windows 10 From: Gary CornellSent: Sunday, August 9, 2020 9:51 AMTo: devCU/IPS-4.4-BitTrackerCc: ZooKeeper-star; MentionSubject: Re: [devCU/IPS-4.4-BitTracker] Is this still alive? (#4) @ZooKeeper-star whats with the css in your posts?Anyway updating the files to 4.4.10 this weekend which will be the final release of the 4.4 tracker obviously since IPS is moving to 4.5 now. Sometime this week will release a basic working tracker. Don't expect too many bells and whistles right now like free leech and stuff. People can easily expand and create plugins later on.BTW we have dropped public tracker usage as this is a secure and private tracker NOT meant to index torrents from other sites or trackers, you HAVE to run your own domain as the tracker or don't bother with this application.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZooKeeper-star** [comment]
Any update? waiting patiently...

**Comment by GaalexxC** [comment]
We will be doing beta testing in about a week or so at my site. If you would like to join the test then email me for more info.

**Comment by ZooKeeper-star** [comment]
Yes please send me the information.
Thanks!

**Comment by ZooKeeper-star** [comment]
Any update?
